# Unless filling for special features, all features should fill for previous forks (starting from Frontier) too
mainnet:
  evm-type: eels
  fill-params: --until=BPO2 --generate-all-formats

benchmark:
  evm-type: benchmark
  fill-params: --fork=Osaka --generate-all-formats --gas-benchmark-values 1,5,10,30,60,100,150 ./tests/benchmark/compute --maxprocesses=30 --dist=worksteal
  feature_only: true

benchmark_fast:
  evm-type: benchmark
  fill-params: --fork=Osaka --generate-all-formats --gas-benchmark-values 100 ./tests/benchmark/compute
  feature_only: true

bal:
  evm-type: eels
  fill-params: --fork=Amsterdam
  feature_only: true
