"""
Merge fixture artifacts from parallel fork workers into a single tarball.

This script takes fixtures generated by parallel fork workers and combines them
into a single release tarball (stable or develop).
"""

import configparser
import json
import os
import shutil
import tarfile
import tempfile
from datetime import datetime
from pathlib import Path

import click

from execution_testing.cli.gen_index import generate_fixtures_index


def extract_fork_fixtures(
    artifacts_dir: Path, fork: str, dest_dir: Path
) -> bool:
    """Extract fixtures for a single fork from its artifact tarball."""
    artifact_dir = artifacts_dir / f"fixtures_{fork}"
    tarball_path = artifact_dir / f"fixtures_{fork}.tar.gz"

    if not tarball_path.exists():
        click.echo(f"Warning: No artifact found for fork {fork} at {tarball_path}")
        return False

    click.echo(f"Extracting {fork} fixtures from {tarball_path}")
    with tarfile.open(tarball_path, "r:gz") as tar:
        tar.extractall(dest_dir)

    return True


def merge_json_files(src_file: Path, dest_file: Path) -> None:
    """Merge JSON fixture files by combining their contents."""
    if not dest_file.exists():
        shutil.copy(src_file, dest_file)
        return

    with open(src_file) as f:
        src_data = json.load(f)

    with open(dest_file) as f:
        dest_data = json.load(f)

    # Merge dictionaries (fixture files are dicts with test IDs as keys)
    dest_data.update(src_data)

    with open(dest_file, "w") as f:
        json.dump(dest_data, f, indent=2)


def merge_fixture_directories(src_dir: Path, dest_dir: Path) -> None:
    """Recursively merge fixture directories, combining JSON files."""
    for item in src_dir.iterdir():
        dest_item = dest_dir / item.name

        if item.is_dir():
            dest_item.mkdir(parents=True, exist_ok=True)
            merge_fixture_directories(item, dest_item)
        elif item.suffix == ".json":
            merge_json_files(item, dest_item)
        else:
            # Copy non-JSON files directly
            shutil.copy(item, dest_item)


def create_fixtures_ini(
    meta_dir: Path, build_name: str, command_line_args: str
) -> None:
    """Create fixtures.ini metadata file."""
    config = configparser.ConfigParser(interpolation=None)
    config["fixtures"] = {
        "timestamp": datetime.now().isoformat(),
        "build": build_name,
        "command_line_args": command_line_args,
    }

    if github_ref := os.getenv("GITHUB_REF"):
        config["fixtures"]["ref"] = github_ref
    if github_sha := os.getenv("GITHUB_SHA"):
        config["fixtures"]["commit"] = github_sha

    config["environment"] = {
        "CI": str(os.getenv("CI", "false")),
    }

    ini_path = meta_dir / "fixtures.ini"
    with open(ini_path, "w") as f:
        f.write("; This file describes fixture build properties\n\n")
        config.write(f)


@click.command()
@click.option(
    "--forks",
    required=True,
    help="JSON array of forks to include (e.g., '[\"Frontier\", \"Homestead\", ...]')",
)
@click.option(
    "--artifacts-dir",
    required=True,
    type=click.Path(exists=True, path_type=Path),
    help="Directory containing fork fixture artifacts",
)
@click.option(
    "--pre-alloc-tar",
    required=True,
    type=click.Path(exists=True, path_type=Path),
    help="Path to pre_alloc_groups.tar.gz",
)
@click.option(
    "--output",
    required=True,
    type=click.Path(path_type=Path),
    help="Output tarball path (e.g., fixtures_stable.tar.gz)",
)
@click.option(
    "--build-name",
    required=True,
    help="Build name for fixtures.ini (e.g., 'stable' or 'develop')",
)
def merge_fork_fixtures(
    forks: str,
    artifacts_dir: Path,
    pre_alloc_tar: Path,
    output: Path,
    build_name: str,
) -> None:
    """
    Merge fixture artifacts from parallel fork workers into a single tarball.
    """
    fork_list = json.loads(forks)
    click.echo(f"Merging fixtures for forks: {fork_list}")
    click.echo(f"Output: {output}")

    with tempfile.TemporaryDirectory() as tmpdir:
        merged_dir = Path(tmpdir) / "fixtures"
        merged_dir.mkdir()
        meta_dir = merged_dir / ".meta"
        meta_dir.mkdir()

        # Extract and merge fixtures from each fork
        for fork in fork_list:
            fork_tmpdir = Path(tmpdir) / f"fork_{fork}"
            fork_tmpdir.mkdir()

            if extract_fork_fixtures(artifacts_dir, fork, fork_tmpdir):
                # Merge into the combined directory
                merge_fixture_directories(fork_tmpdir, merged_dir)

        # Extract and add pre_alloc groups to blockchain_tests_engine_x
        engine_x_dir = merged_dir / "blockchain_tests_engine_x"
        engine_x_dir.mkdir(parents=True, exist_ok=True)

        click.echo(f"Extracting pre_alloc groups from {pre_alloc_tar}")
        with tarfile.open(pre_alloc_tar, "r:gz") as tar:
            tar.extractall(engine_x_dir)

        # Generate index.json using the existing gen_index module
        click.echo("Generating index.json...")
        generate_fixtures_index(merged_dir, quiet_mode=False, force_flag=True)

        # Create fixtures.ini
        create_fixtures_ini(
            meta_dir,
            build_name,
            f"merge_fork_fixtures.py --forks '{forks}' --build-name {build_name}",
        )

        # Create the output tarball
        click.echo(f"Creating {output}...")
        with tarfile.open(output, "w:gz") as tar:
            tar.add(merged_dir, arcname="fixtures")

        click.echo(f"Successfully created {output}")


if __name__ == "__main__":
    merge_fork_fixtures()
