[tox]
min_version = 4.0
requires =
    tox-uv >=0.2.0
envlist = py3,pypy3,json_infra,static,eest-lint,eest-typecheck,eest-spellcheck,eest-pytest,eest-tests-deployed,eest-tests-deployed-benchmark,eest-tests-develop

[testenv]
package = uv
uv_seed = false

[testenv:static]
extras =
    lint
    optimized
    test
    doc
commands =
    codespell -I whitelist.txt {tox_root}/src --skip '{tox_root}/src/ethereum_spec_tests'
    ruff check src --exclude src/ethereum_spec_tests
    mypy src --exclude "src/ethereum_spec_tests/*" --namespace-packages
    ethereum-spec-lint
    uv lock --check

[testenv:json_infra]
extras =
    test
commands =
    pytest \
        -m "not slow" \
        -n auto --maxprocesses 6 \
        --cov-config=pyproject.toml \
        --cov=ethereum \
        --cov-report=term \
        --cov-report "xml:{toxworkdir}/coverage.xml" \
        --no-cov-on-fail \
        --cov-branch \
        --ignore-glob='tests/json_infra/fixtures/*' \
        --basetemp="{temp_dir}/pytest" \
        tests/json_infra

[testenv:py3]
extras =
    test,fill
commands =
    ethereum-spec-fill \
        -m "not slow and not zkevm and not benchmark" \
        -n auto --maxprocesses 6 \
        --basetemp="{temp_dir}/pytest" \
        --clean \
        --until Osaka \
        tests/eest

[testenv:pypy3]
extras =
    test,fill
passenv =
    PYPY_GC_MAX
commands =
    ethereum-spec-fill \
        --tb=no \
        --show-capture=no \
        --disable-warnings \
        -m "not slow and not zkevm and not benchmark" \
        -n auto --maxprocesses 3 \
        --basetemp="{temp_dir}/pytest" \
        --clean \
        --until Osaka \
        tests/eest

[testenv:optimized]
extras =
    test
    optimized
passenv =
    PYPY_GC_MAX
commands =
    pytest \
        -m "not slow and not evm_tools" \
        -n auto --maxprocesses 5 \
        --ignore-glob='tests/json_infra/fixtures/*' \
        --ignore-glob='tests/test_t8n.py' \
        --ignore-glob='eest_tests/*' \
        --basetemp="{temp_dir}/pytest" \
        --optimized \
        tests/json_infra

[testenv:doc]
basepython = python3
extras = doc
commands =
    docc --output "{toxworkdir}/docs"
    python -c 'import pathlib; print("documentation available under file://\{0\}".format(pathlib.Path(r"{toxworkdir}") / "docs" / "index.html"))'


[eest]
runner = uv-venv-lock-runner
package = editable
wheel_build_env = .pkg
python_source_dirs = src/ethereum_spec_tests tests/eest # .github/scripts
ruff_config = ruff.eest.toml
mypy_config = mypy.eest.ini

[testenv:eest-lint]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Lint and code formatting checks (ruff)
extras = lint
commands =
    ruff check --config {[eest]ruff_config} --no-fix --show-fixes {[eest]python_source_dirs}
    ruff format --config {[eest]ruff_config} --check {[eest]python_source_dirs}

[testenv:eest-typecheck]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Run type checking (mypy)
extras = test,fill,lint
commands = mypy --config-file {[eest]mypy_config} {[eest]python_source_dirs}


[testenv:eest-pytest]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Run library and framework unit tests (pytest)
setenv =
    # Use custom EELS_RESOLUTIONS_FILE if it is set via the environment (eg, in CI)
    EELS_RESOLUTIONS_FILE = {env:EELS_RESOLUTIONS_FILE:}
    CI = {env:CI:}
extras =
    test
    fill
    lint # Required `gentest` for formatting tests
commands =
    pytest -n auto ./src/ethereum_spec_tests


[forks]
develop = Osaka
eip7692 = EOFv1

[testenv:eest-tests-deployed]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Fill test cases in ./tests/ for deployed mainnet forks, except for slow/benchmark tests.
extras = test,fill
setenv =
    # Use custom EELS_RESOLUTIONS_FILE if it is set via the environment (eg, in CI)
    EELS_RESOLUTIONS_FILE = {env:EELS_RESOLUTIONS_FILE:}
commands = ethereum-spec-fill -n auto -m "not slow" --output=/tmp/fixtures-tox --clean

[testenv:eest-tests-deployed-benchmark]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Fill benchmarking test cases in ./tests/ for deployed mainnet forks, using evmone-t8n.
extras = test,fill
commands = ethereum-spec-fill -n auto -m "benchmark" --gas-benchmark-values 5 --output=/tmp/fixtures-tox --clean --evm-bin=evmone-t8n

[testenv:eest-tests-develop]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Fill test cases in ./tests/ for deployed and development mainnet forks
setenv =
    # Use custom EELS_RESOLUTIONS_FILE if it is set via the environment (eg, in CI)
    EELS_RESOLUTIONS_FILE = {env:EELS_RESOLUTIONS_FILE:}
extras = test,fill
commands = ethereum-spec-fill -n auto --until={[forks]develop} -k "not slow" --output=/tmp/fixtures-tox --clean

# ----------------------------------------------------------------------------------------------
# ALIAS ENVIRONMENTS
# ----------------------------------------------------------------------------------------------
# For convenience/backwards compatibility. Using -e with a list of environments is preferred due
# to clearer output and better parallelization, e.g.
# uvx --with=tox-uv tox -e lint,typecheck,spellcheck,pytest
# ----------------------------------------------------------------------------------------------

# ALIAS that runs checks on ./src/: lint, typecheck, spellcheck, pytest
# uvx --with=tox-uv tox -e lint,typecheck,spellcheck,pytest
[testenv:eest-framework]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Alias that runs lint, typecheck, spellcheck, pytest.
extras =
    {[testenv:eest-lint]extras}
    {[testenv:eest-typecheck]extras}
    {[testenv:eest-spellcheck]extras}
    {[testenv:eest-pytest]extras}
setenv =
    {[testenv:eest-pytest]setenv}
commands_pre =
    {[testenv:eest-pytest]:commands_pre}
commands =
    {[testenv:eest-lint]commands}
    {[testenv:eest-typecheck]commands}
    {[testenv:eest-spellcheck]commands}
    {[testenv:eest-pytest]commands}

# ALIAS that runs checks on ./tests/: lint, typecheck, spellcheck, tests-deployed
# uvx --with=tox-uv tox -e lint,typecheck,spellcheck,tests-deployed
[testenv:eest-tests]
runner = {[eest]runner}
package = {[eest]package}
wheel_build_env = {[eest]wheel_build_env}
description = Alias that runs lint, typecheck, spellcheck, tests-deployed
extras =
    {[testenv:eest-lint]extras}
    {[testenv:eest-typecheck]extras}
    {[testenv:eest-spellcheck]extras}
    {[testenv:eest-tests-deployed]extras}
    {[testenv:eest-tests-deployed-benchmark]extras}
setenv =
    {[testenv:eest-pytest]setenv}
commands_pre =
    {[testenv:eest-tests-deployed]:commands_pre}
    {[testenv:eest-tests-deployed-benchmark]:commands_pre}
commands =
    {[testenv:eest-lint]commands}
    {[testenv:eest-typecheck]commands}
    {[testenv:eest-spellcheck]commands}
    {[testenv:eest-tests-deployed]commands}
    {[testenv:eest-tests-deployed-benchmark]commands}
