[tox]
requires =
    tox>=4,<5
    tox-uv>=1.29,<2
envlist = py3,pypy3,json_infra,static,tests_pytest_py3,tests_pytest_pypy3

[testenv]
runner = uv-venv-lock-runner
uv_seed = false
wheel_build_env = .pkg

[testenv:static]
commands =
    codespell -I whitelist.txt src tests/evm_tools tests/json_infra packages docs src/ethereum_spec_tests tests packages/testing
    ruff check src packages tests --exclude tests/fixtures
    ruff format src packages tests --check
    mypy
    ethereum-spec-lint
    uv lock --check

[testenv:tests_pytest_py3]
changedir = {toxinidir}/packages/testing
package = editable
commands =
    pytest \
        -n auto --maxprocesses 6 \
        --basetemp="{temp_dir}/pytest" \
        src

[testenv:tests_pytest_pypy3]
# overwrite default groups (dev) to avoid installing optimized in tox envs using pypy
dependency_groups =
    test
    lint  # TODO: add ruff for gentest; remove as part of ethereum/execution-specs#1715
passenv =
    PYPY_GC_MAX
    PYPY_GC_MIN
# run inside the package directory so pytest picks up packages/testing/pyproject.toml
changedir = {toxinidir}/packages/testing
package = editable
commands =
    pytest \
        -n auto --maxprocesses 6 \
        --basetemp="{temp_dir}/pytest" \
        src

[testenv:json_infra]
commands =
    pytest \
        -m "not slow" \
        -n auto --maxprocesses 6 \
        --cov-config=pyproject.toml \
        --cov=ethereum \
        --cov-report=term \
        --cov-report "xml:{toxworkdir}/coverage.xml" \
        --no-cov-on-fail \
        --cov-branch \
        --ignore-glob='tests/json_infra/fixtures/*' \
        --basetemp="{temp_dir}/pytest" \
        tests/json_infra

[testenv:py3]
commands =
    fill \
        -m "not slow and not zkevm and not benchmark" \
        -n auto --maxprocesses 10 --dist=loadgroup \
        --basetemp="{temp_dir}/pytest" \
        --log-to "{toxworkdir}/logs" \
        --clean \
        --until Osaka \
        tests

[testenv:pypy3]
# see comment for tests_pytest_pypy3
dependency_groups =
    test
passenv =
    PYPY_GC_MAX
    PYPY_GC_MIN
commands =
    fill \
        --skip-index \
        --no-html \
        --tb=no \
        --show-capture=no \
        --disable-warnings \
        -m "not slow and not zkevm and not benchmark" \
        -n auto --maxprocesses 7 --dist=loadgroup \
        --basetemp="{temp_dir}/pytest" \
        --log-to "{toxworkdir}/logs" \
        --clean \
        --until Osaka \
        tests

[testenv:optimized]
passenv =
    PYPY_GC_MAX
    PYPY_GC_MIN
commands =
    pytest \
        -m "not slow and not evm_tools" \
        -n auto --maxprocesses 5 \
        --ignore-glob='tests/json_infra/fixtures/*' \
        --ignore-glob='tests/test_t8n.py' \
        --basetemp="{temp_dir}/pytest" \
        --optimized \
        tests/json_infra

[testenv:spec-docs]
description = Generate documentation for the specification code using docc
basepython = python3
commands =
    docc --output "{toxworkdir}/docs"
    python -c 'import pathlib; print("documentation available under file://\{0\}".format(pathlib.Path(r"{toxworkdir}") / "docs" / "index.html"))'

[testenv:changelog]
description = Validate EEST changelog entries
dependency_groups = docs
changedir = {toxinidir}/packages/testing
allowlist_externals = uv
commands_pre = uv pip install -e {toxinidir}/packages/testing
commands = validate_changelog

[testenv:mkdocs]
description = Build EEST documentation with mkdocs
dependency_groups = docs,lint
setenv =
    GEN_TEST_DOC_VERSION = "tox"
    # Required for `cairosvg` so tox can find `libcairo-2`?
    # https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/?h=cairo#cairo-library-was-not-found
package = editable
commands =
    ruff check --no-fix --show-fixes docs/scripts/
    ruff format --check docs/scripts/
    mkdocs build --strict

[testenv:markdownlint]
description = Lint EEST markdown files (markdownlint)
dependency_groups = docs
changedir = {toxinidir}/packages/testing
allowlist_externals = uv
commands_pre = uv pip install -e {toxinidir}/packages/testing
commands = markdownlintcli2_soft_fail

[testenv:check-docs]
description = Runs all documentation checks (spellcheck, markdownlint, mkdocs)
dependency_groups =
    {[testenv:test-docs]dependency_groups}
package = editable
setenv =
    {[testenv:test-docs]setenv}
commands =
    codespell -I whitelist.txt docs
    {[testenv:markdownlint]commands}
    {[testenv:mkdocs]commands}
