class PublicKey:
    @classmethod
    def from_signature_and_message(
        cls, signature: bytes, message: bytes
    ) -> "PublicKey": ...
    @classmethod
    def from_secret(cls, secret: bytes) -> "PublicKey": ...
    def format(self, compressed: bool = True) -> bytes: ...

class PrivateKey:
    public_key: PublicKey
    def __init__(self, secret: bytes) -> None: ...
    def sign_recoverable(self, message: bytes) -> bytes: ...
