"""
Index tables commit to the searchable contents of recent blocks, originally
defined in [EIP-8304].

Logs are cheap to emit but have long been expensive to find. The bloom filter
carried by each block header is saturated to the point of uselessness, leaving
users to trust whichever provider answers their queries. An _index table_
replaces that trust with a proof. It is a list of _index entries_, each one
pairing a searchable value -- a block hash, a transaction hash, the address
that emitted a log, or one of that log's topics -- with the position where it
occurs. Entries are ordered by their binary encoding, so a proof of the
entries surrounding a queried value reveals both which matches exist and that
none were left out.

A table covers a range of consecutive blocks. One table is built per block and
tables of adjacent ranges merge into the larger tables of the level above,
with the number of blocks each level covers given by [`TABLE_SIZES`][sizes].
Merging is concatenation followed by a sort, so a merged table is
indistinguishable from one built from its blocks directly. The root of every
table, computed by [`compute_table_root`][root], is handed to the index
contract, which keeps a ring buffer of roots for each level.

Block entries trail their table by one block: the table of block `N` carries
the hash of block `N - 1`, since a block's own hash is not yet known while it
is being processed.

[EIP-8304]: https://eips.ethereum.org/EIPS/eip-8304
[sizes]: ref:ethereum.forks.amsterdam.index_tables.TABLE_SIZES
[root]: ref:ethereum.forks.amsterdam.index_tables.compute_table_root
"""

from hashlib import sha256
from typing import Dict, List, Optional, Tuple

from ethereum_types.bytes import Bytes, Bytes32
from ethereum_types.numeric import Uint, ulen

from ethereum.crypto.hash import Hash32
from ethereum.utils.byte import left_pad_zero_bytes

from .blocks import Log

IndexEntry = Bytes
"""
Binary encoding of one searchable value together with its position.
"""

IndexTable = Tuple[IndexEntry, ...]
"""
Entries generated by a range of consecutive blocks, in ascending order.
"""

TABLE_SIZES = (Uint(1), Uint(4), Uint(16), Uint(64), Uint(256))
"""
Blocks covered by a table on each level, from the lowest level upwards.

Each size is a multiple of the one below it, so a table always merges from a
whole number of tables of the preceding level.
"""

RETAINED_BLOCKS = TABLE_SIZES[-1] * Uint(5) // Uint(4) - Uint(1)
"""
Blocks whose tables have to be kept around to build every mandated table.

The largest table is published well after the range it covers has been
processed, so its blocks have to outlive both that range and the delay.
"""

ENTRY_TYPE_LENGTH = 2
"""
Bytes reserved for the type identifier that begins every entry.
"""

BLOCK_ENTRY = Uint(0)
"""
Entry type recording the hash of a block.
"""

TRANSACTION_ENTRY = Uint(1)
"""
Entry type recording the hash of a transaction.
"""

LOG_ADDRESS_ENTRY = Uint(2)
"""
Entry type recording the address that emitted a log.
"""

FIRST_LOG_TOPIC_ENTRY = Uint(3)
"""
Entry type recording a log's first topic; later topics follow in order.
"""

ZERO_LEAF = Bytes32(b"\x00" * 32)
"""
Leaf that fills out a table's tree when its entries do not fill the last
level.
"""


def encode_entry_type(entry_type: Uint) -> Bytes:
    """
    Encode the identifier that begins every entry of a given type.
    """
    return left_pad_zero_bytes(entry_type.to_be_bytes(), ENTRY_TYPE_LENGTH)


def encode_block_entry(block_number: Uint, block_hash: Hash32) -> IndexEntry:
    """
    Encode the entry that makes the block at `block_number` searchable by its
    hash.
    """
    return (
        encode_entry_type(BLOCK_ENTRY)
        + block_hash
        + block_number.to_be_bytes8()
    )


def encode_transaction_entries(
    block_number: Uint,
    index: Uint,
    tx_hash: Hash32,
    cumulative_log_count: Uint,
    logs: Tuple[Log, ...],
) -> Tuple[IndexEntry, ...]:
    """
    Encode the entries that make a transaction and its `logs` searchable.

    Log indices count from the beginning of the transaction, so the
    `cumulative_log_count` recorded alongside the transaction -- the number of
    logs emitted earlier in the block -- is what relates them to the block as
    a whole.
    """
    position = block_number.to_be_bytes8() + index.to_be_bytes4()
    entries = [
        encode_entry_type(TRANSACTION_ENTRY)
        + tx_hash
        + position
        + cumulative_log_count.to_be_bytes4()
    ]

    for log_index, log in enumerate(logs):
        occurrence = position + Uint(log_index).to_be_bytes4()
        entries.append(
            encode_entry_type(LOG_ADDRESS_ENTRY) + log.address + occurrence
        )
        for topic_index, topic in enumerate(log.topics):
            entries.append(
                encode_entry_type(FIRST_LOG_TOPIC_ENTRY + Uint(topic_index))
                + topic
                + occurrence
            )

    return tuple(entries)


def merge_tables(
    tables: Dict[Uint, IndexTable], first_block: Uint, table_size: Uint
) -> Optional[IndexTable]:
    """
    Merge the single block tables covering `table_size` blocks from
    `first_block` onwards.

    Nothing is merged when any block of the range has no table of its own,
    which is how a range reaching back beyond the activation of index tables
    is recognised.
    """
    merged: List[IndexEntry] = []

    for offset in range(int(table_size)):
        table = tables.get(first_block + Uint(offset))
        if table is None:
            return None
        merged += table

    return tuple(sorted(merged))


def compute_table_root(table: IndexTable) -> Hash32:
    """
    Compute the root hash committing to every entry of `table`.

    Entries are hashed with SHA2-256 into the leaves of a binary tree of the
    smallest depth that holds them, and the entry count is mixed into the
    result so tables of differing lengths cannot share a root. This is the
    [SSZ] `hash_tree_root` of a list of hashes whose limit is its own length.

    [SSZ]: https://github.com/ethereum/consensus-specs/blob/dev/ssz/simple-serialize.md
    """  # noqa: E501
    layer = [Bytes32(sha256(entry).digest()) for entry in table]
    root = ZERO_LEAF

    if layer:
        while len(layer) & (len(layer) - 1) != 0:
            layer.append(ZERO_LEAF)

        while len(layer) > 1:
            layer = [
                Bytes32(sha256(layer[i] + layer[i + 1]).digest())
                for i in range(0, len(layer), 2)
            ]

        root = layer[0]

    return Hash32(sha256(root + ulen(table).to_le_bytes32()).digest())
