"""
Fork rules for consume hive simulators.

TODO: Create the ruleset dynamically per fixture test case based on the fork.
Remove this file afterwards.
"""

from typing import Dict, List

from execution_testing.forks import (
    BPO1,
    BPO2,
    BPO3,
    BPO4,
    BPO5,
    Amsterdam,
    Berlin,
    BerlinToLondonAt5,
    BPO1ToBPO2AtTime15k,
    BPO2ToBPO3AtTime15k,
    BPO3ToBPO4AtTime15k,
    BPO4ToBPO5AtTime15k,
    BPO5ToAmsterdamAtTime15k,
    Byzantium,
    Cancun,
    CancunToPragueAtTime15k,
    Constantinople,
    ConstantinopleFix,
    Fork,
    Frontier,
    Homestead,
    Istanbul,
    London,
    Osaka,
    OsakaToBPO1AtTime15k,
    Paris,
    ParisToShanghaiAtTime15k,
    Prague,
    PragueToOsakaAtTime15k,
    Shanghai,
    ShanghaiToCancunAtTime15k,
)


def get_blob_schedule_entries(fork: Fork) -> Dict[str, int]:
    """
    Generate blob schedule entries for each fork (and respective parent forks).

    Adds the following entries to the ruleset for the given fork (and parent
    forks):
      HIVE_{FORK}_BLOB_TARGET: target_blobs_per_block()
      HIVE_{FORK}_BLOB_MAX: max_blobs_per_block()
      HIVE_{FORK}_BLOB_BASE_FEE_UPDATE_FRACTION: blob_base_fee_update_
                                                 fraction()
    """
    entries: Dict = {}
    forks_with_blobs: List[Fork] = []
    current_fork = fork

    # Walk up the parent chain to collect all forks with blob support
    while current_fork.supports_blobs():
        forks_with_blobs.append(current_fork)
        current_fork = current_fork.parent()  # type: ignore

    # Special case: For forks that come after BPOs but don't inherit from them
    # (e.g., Amsterdam and any future forks), include BPO fork configs.
    # This allows the genesis to support both:
    # - Osaka -> Amsterdam (skips BPOs, uses Osaka blob params)
    # - Osaka -> BPO1 -> ... -> Amsterdam (uses BPO params chronologically)
    bpo_forks = [BPO1, BPO2, BPO3, BPO4, BPO5]
    has_bpo_in_chain = any(bpo_fork in forks_with_blobs for bpo_fork in bpo_forks)

    # If this fork doesn't have BPO in its inheritance chain but comes after Osaka,
    # add all BPO forks so they can be configured in the genesis
    if not has_bpo_in_chain and Osaka in forks_with_blobs:
        for bpo_fork in bpo_forks:
            forks_with_blobs.append(bpo_fork)

    # Generate blob schedule entries for all collected forks
    for fork_to_process in forks_with_blobs:
        prefix = fork_to_process.__name__.upper()
        entries[f"HIVE_{prefix}_BLOB_TARGET"] = (
            fork_to_process.target_blobs_per_block()
        )
        entries[f"HIVE_{prefix}_BLOB_MAX"] = (
            fork_to_process.max_blobs_per_block()
        )
        entries[f"HIVE_{prefix}_BLOB_BASE_FEE_UPDATE_FRACTION"] = (
            fork_to_process.blob_base_fee_update_fraction()
        )
    return entries


ruleset: Dict[Fork, Dict[str, int]] = {
    Frontier: {
        "HIVE_FORK_HOMESTEAD": 2000,
        "HIVE_FORK_DAO_BLOCK": 2000,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    Homestead: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_DAO_BLOCK": 2000,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    Byzantium: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    Constantinople: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    ConstantinopleFix: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    Istanbul: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    Berlin: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 2000,
    },
    BerlinToLondonAt5: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 5,
    },
    London: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
    },
    Paris: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
    },
    Shanghai: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
    },
    ParisToShanghaiAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 15000,
    },
    Cancun: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        **get_blob_schedule_entries(Cancun),
    },
    ShanghaiToCancunAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 15000,
        **get_blob_schedule_entries(Cancun),
    },
    Prague: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        **get_blob_schedule_entries(Prague),
    },
    CancunToPragueAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 15000,
        **get_blob_schedule_entries(Prague),
    },
    Osaka: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        **get_blob_schedule_entries(Osaka),
    },
    PragueToOsakaAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 15000,
        **get_blob_schedule_entries(Osaka),
    },
    BPO1: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO1),
    },
    OsakaToBPO1AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO1),
    },
    BPO2: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO2),
    },
    BPO1ToBPO2AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO2),
    },
    BPO3: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO3),
    },
    BPO2ToBPO3AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO3),
    },
    BPO4: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO4),
    },
    BPO3ToBPO4AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO4),
    },
    BPO5: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 0,
        "HIVE_BPO5_TIMESTAMP": 0,
        **get_blob_schedule_entries(BPO5),
    },
    BPO4ToBPO5AtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 0,
        "HIVE_BPO5_TIMESTAMP": 15000,
        **get_blob_schedule_entries(BPO5),
    },
    BPO5ToAmsterdamAtTime15k: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 0,
        "HIVE_BPO5_TIMESTAMP": 0,
        "HIVE_AMSTERDAM_TIMESTAMP": 15000,
        **get_blob_schedule_entries(Amsterdam),
    },
    Amsterdam: {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        "HIVE_BPO1_TIMESTAMP": 0,
        "HIVE_BPO2_TIMESTAMP": 0,
        "HIVE_BPO3_TIMESTAMP": 0,
        "HIVE_BPO4_TIMESTAMP": 0,
        "HIVE_BPO5_TIMESTAMP": 0,
        "HIVE_AMSTERDAM_TIMESTAMP": 0,
        **get_blob_schedule_entries(Amsterdam),
    },
}
