"""
EVM Object Format generic constants.
Applicable to EOF version 1.
"""

from ..constants import VERSION_BYTE_LENGTH

VERSION_NUMBER = 0x01

VERSION_NUMBER_BYTES = VERSION_NUMBER.to_bytes(VERSION_BYTE_LENGTH, "big")

MAX_CODE_SECTIONS = 1024

MAX_RETURN_STACK_HEIGHT = 1024

MAX_OPERAND_STACK_HEIGHT = 1023

MAX_CODE_INPUTS = 127

MAX_CODE_OUTPUTS = 127

NON_RETURNING_SECTION = 0x80

MAX_RJUMPV_COUNT = 0xFF

MAX_BYTECODE_SIZE = 24576

MAX_INITCODE_SIZE = MAX_BYTECODE_SIZE * 2

HEADER_SECTION_KIND_BYTE_LENGTH = 1

HEADER_SECTION_COUNT_BYTE_LENGTH = 2

HEADER_SECTION_SIZE_BYTE_LENGTH = 2

TYPES_INPUTS_BYTE_LENGTH = 1

TYPES_OUTPUTS_BYTE_LENGTH = 1

TYPES_STACK_BYTE_LENGTH = 2
