"""
Tests validator deposit functionality.

Tests the validator deposit functionality implementation from
[EIP-6110: Supply validator deposits on chain](https://eips.ethereum.org/EIPS/eip-6110).
"""

from typing import List

import pytest
from execution_testing import (
    Account,
    Alloc,
    Block,
    BlockchainTestFiller,
    BlockException,
    DepositRequest,
    Environment,
    Fork,
    Hash,
    Header,
    Macros,
    Op,
    Requests,
    SystemContractInteractionContract,
    SystemContractInteractionTransaction,
    Transaction,
    While,
)

from .helpers import deposit_contract_execution_gas
from .spec import Spec, ref_spec_6110

REFERENCE_SPEC_GIT_PATH = ref_spec_6110.git_path
REFERENCE_SPEC_VERSION = ref_spec_6110.version

pytestmark = pytest.mark.valid_from("Prague")


@pytest.mark.parametrize(
    "requests",
    [
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_eoa",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=120_000_000_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_eoa_huge_amount",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x1,
                        ),
                    ],
                ),
            ],
            id="multiple_deposit_from_same_eoa",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=i,
                        )
                        for i in range(200)
                    ],
                )
            ],
            id="multiple_deposit_from_same_eoa_high_count",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x1,
                        )
                    ],
                ),
            ],
            id="multiple_deposit_from_different_eoa",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=999_999_999,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                    ],
                ),
            ],
            id="multiple_deposit_from_same_eoa_first_reverts",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=999_999_999,
                            signature=0x03,
                            index=0x0,
                        ),
                    ],
                ),
            ],
            id="multiple_deposit_from_same_eoa_last_reverts",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            calldata_modifier=lambda _: b"",
                            valid=False,
                        )
                    ],
                ),
            ],
            id="send_eth_from_eoa",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                            calldata_modifier=lambda _: b"",
                        )
                    ],
                ),
            ],
            # TODO: EIP-5920: Send using PAY opcode
            id="send_eth_to_contract_no_deposit_data",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_contract",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x1,
                        ),
                    ],
                ),
            ],
            id="multiple_deposits_from_contract",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=i,
                        )
                        for i in range(450)
                    ],
                ),
            ],
            id="many_deposits_from_contract",
            marks=pytest.mark.slow,
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=999_999_999,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                    ],
                ),
            ],
            id="multiple_deposits_from_contract_first_reverts",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=999_999_999,
                            signature=0x03,
                            index=0x1,
                            valid=False,
                        ),
                    ],
                ),
            ],
            id="multiple_deposits_from_contract_last_reverts",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x1,
                            valid=False,
                        ),
                    ],
                    extra_code=Op.REVERT(0, 0),
                ),
            ],
            id="multiple_deposits_from_contract_caller_reverts",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x1,
                            valid=False,
                        ),
                    ],
                    extra_code=Macros.OOG(),
                ),
            ],
            id="multiple_deposits_from_contract_caller_oog",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                    ],
                ),
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x1,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_contract_single_deposit_from_eoa",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x1,
                        ),
                    ],
                ),
            ],
            id="single_deposit_from_eoa_single_deposit_from_contract",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x1,
                        ),
                    ],
                ),
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x2,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_contract_between_eoa_deposits",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                    ],
                ),
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x1,
                        )
                    ],
                ),
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x2,
                        ),
                    ],
                ),
            ],
            id="single_deposit_from_eoa_between_contract_deposits",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        )
                    ],
                    call_type=Op.DELEGATECALL,
                ),
            ],
            id="single_deposit_from_contract_delegatecall",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        )
                    ],
                    call_type=Op.STATICCALL,
                ),
            ],
            id="single_deposit_from_contract_staticcall",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        )
                    ],
                    call_type=Op.CALLCODE,
                ),
            ],
            id="single_deposit_from_contract_callcode",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                    call_depth=3,
                ),
            ],
            id="single_deposit_from_contract_call_depth_3",
        ),
        # TODO: Provide a higher transaction gas limit for EIP-8037 state
        # creation gas costs to extend this test past EIP8037.
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                    call_depth=271,
                ),
            ],
            id="single_deposit_from_contract_call_depth_high",
            marks=pytest.mark.valid_before("EIP8037"),
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_001,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_eoa_minimum_plus_one",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                            extra_wei=1,
                            valid=False,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_eoa_minimum_plus_one_wei",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                            extra_wei=-1,
                            valid=False,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_eoa_minimum_minus_one_wei",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                            extra_wei=1,
                            valid=False,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_contract_minimum_plus_one_wei",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                            extra_wei=-1,
                            valid=False,
                        )
                    ],
                ),
            ],
            id="single_deposit_from_contract_minimum_minus_one_wei",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_001,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=999_999_999,
                            signature=0x03,
                            index=0x1,
                            valid=False,
                        ),
                    ],
                ),
            ],
            id="multiple_deposits_from_eoa_minimum_plus_one_minimum_minus_one",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        )
                    ],
                    # Send 32 ETH minus 1 wei to the contract, note
                    # `DepositRequest.amount` is in gwei
                    tx_value=32_000_000_000 * 10**9 - 1,
                    contract_balance=0,
                ),
            ],
            id="send_not_enough_eth_to_contract_with_zero_balance",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=999_999_999,
                            signature=0x03,
                            index=0x0,
                            valid=False,
                        )
                    ],
                    tx_value=1_000_000_000 * 10**9,
                ),
            ],
            id="send_eth_to_contract_insufficient_deposit",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                    # Send 32 ETH (in wei) to the contract
                    tx_value=32_000_000_000 * 10**9,
                    contract_balance=0,
                ),
            ],
            id="send_exact_eth_amount_for_deposit",
        ),
        pytest.param(
            [
                SystemContractInteractionContract(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=32_000_000_000,
                            signature=0x03,
                            index=0x1,
                        ),
                    ],
                    # Send 64 ETH (in wei) to the contract
                    tx_value=64_000_000_000 * 10**9,
                    contract_balance=0,
                ),
            ],
            id="send_exact_eth_amount_for_multiple_deposits",
        ),
    ],
)
@pytest.mark.slow()
def test_deposit(
    blockchain_test: BlockchainTestFiller,
    pre: Alloc,
    blocks: List[Block],
) -> None:
    """Test making a deposit to the beacon chain deposit contract."""
    blockchain_test(
        pre=pre,
        post={},
        blocks=blocks,
    )


@pytest.mark.parametrize(
    "requests,block_body_override_requests,exception",
    [
        pytest.param(
            [],
            [
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x0,
                ),
            ],
            BlockException.INVALID_REQUESTS,
            id="no_deposits_non_empty_requests_list",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            [],
            BlockException.INVALID_REQUESTS,
            id="single_deposit_empty_requests_list",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            [
                DepositRequest(
                    pubkey=0x02,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x0,
                )
            ],
            BlockException.INVALID_REQUESTS,
            id="single_deposit_pubkey_mismatch",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            [
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x03,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x0,
                )
            ],
            BlockException.INVALID_REQUESTS,
            id="single_deposit_credentials_mismatch",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            [
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=2_000_000_000,
                    signature=0x03,
                    index=0x0,
                )
            ],
            BlockException.INVALID_REQUESTS,
            id="single_deposit_amount_mismatch",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            [
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x04,
                    index=0x0,
                )
            ],
            BlockException.INVALID_REQUESTS,
            id="single_deposit_signature_mismatch",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            [
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x1,
                )
            ],
            BlockException.INVALID_REQUESTS,
            id="single_deposit_index_mismatch",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        ),
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x1,
                        ),
                    ],
                ),
            ],
            [
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x1,
                ),
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x0,
                ),
            ],
            BlockException.INVALID_REQUESTS,
            id="two_deposits_out_of_order",
        ),
        pytest.param(
            [
                SystemContractInteractionTransaction(
                    requests=[
                        DepositRequest(
                            pubkey=0x01,
                            withdrawal_credentials=0x02,
                            amount=1_000_000_000,
                            signature=0x03,
                            index=0x0,
                        )
                    ],
                ),
            ],
            [
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x0,
                ),
                DepositRequest(
                    pubkey=0x01,
                    withdrawal_credentials=0x02,
                    amount=1_000_000_000,
                    signature=0x03,
                    index=0x0,
                ),
            ],
            BlockException.INVALID_REQUESTS,
            id="single_deposit_duplicate_in_requests_list",
        ),
    ],
)
@pytest.mark.exception_test
def test_deposit_negative(
    blockchain_test: BlockchainTestFiller,
    pre: Alloc,
    blocks: List[Block],
) -> None:
    """
    Test producing a block with the incorrect deposits in the body of the
    block, and/or Engine API payload.
    """
    blockchain_test(
        pre=pre,
        post={},
        blocks=blocks,
    )


@pytest.mark.parametrize(
    "deposit_count",
    [
        pytest.param(
            Spec.MAX_DEPOSIT_REQUESTS_PER_PAYLOAD + 1,
            id="over_consensus_layer_payload_maximum",
        ),
    ],
)
@pytest.mark.slow()
def test_deposit_high_count(
    blockchain_test: BlockchainTestFiller,
    pre: Alloc,
    fork: Fork,
    deposit_count: int,
) -> None:
    """
    Test a single block carrying more deposits than a consensus layer payload
    is allowed to contain, since EIP-6110 leaves the execution layer request
    list unbounded.

    The deposits are driven by a relay contract that loops over one deposit
    call, so they only differ in the index the deposit contract assigns them.
    """
    deposit = DepositRequest(
        pubkey=0x01,
        withdrawal_credentials=0x02,
        amount=Spec.MIN_DEPOSIT_AMOUNT,
        signature=0x03,
        index=0x0,
    )
    sender = pre.fund_eoa()

    relay_setup_code = Op.CALLDATACOPY(
        0, 32, len(deposit.calldata)
    ) + Op.CALLDATALOAD(0)
    relay_loop_code = While(
        body=Op.POP(
            Op.CALL(
                address=deposit.system_contract_address,
                value=deposit.value,
                args_offset=0,
                args_size=len(deposit.calldata),
                value_transfer=True,
                address_warm=True,
            )
        ),
        condition=Op.PUSH1(1) + Op.SWAP1 + Op.SUB + Op.DUP1,
    )

    deposit_relay_code = relay_setup_code + relay_loop_code
    deposit_relay_iteration_gas = relay_loop_code.gas_cost(fork)

    relay_contract = pre.deploy_contract(
        code=deposit_relay_code,
        balance=deposit.value * deposit_count,
    )

    intrinsic_gas_calculator = fork.transaction_intrinsic_cost_calculator()
    # The deposit contract's Merkle branch loop runs once per trailing zero
    # bit of the new deposit count, so no deposit iterates it more often than
    # the count's bit length. Budgeting that depth for every deposit, rather
    # than the single iteration they average, leaves room for the storage
    # slots each transaction writes for the first time.
    gas_per_deposit = (
        deposit_relay_iteration_gas
        + deposit_contract_execution_gas(
            fork, branch_updates=deposit_count.bit_length()
        )
    )

    deposits_per_transaction = deposit_count
    gas_limit_cap = fork.transaction_gas_limit_cap()
    if gas_limit_cap is not None:
        deposits_per_transaction = (
            gas_limit_cap
            - intrinsic_gas_calculator(
                calldata=Hash(deposit_count) + deposit.calldata
            )
            - relay_setup_code.gas_cost(fork)
        ) // gas_per_deposit

    txs: List[Transaction] = []
    for start in range(0, deposit_count, deposits_per_transaction):
        count = min(deposits_per_transaction, deposit_count - start)
        data = Hash(count) + deposit.calldata
        txs.append(
            Transaction(
                sender=sender,
                to=relay_contract,
                data=data,
                gas_limit=intrinsic_gas_calculator(calldata=data)
                + (count * gas_per_deposit),
            )
        )

    blockchain_test(
        genesis_environment=Environment(
            gas_limit=sum(int(tx.gas_limit) for tx in txs)
        ),
        pre=pre,
        post={relay_contract: Account(balance=0)},
        blocks=[
            Block(
                txs=txs,
                header_verify=Header(
                    requests_hash=Requests(
                        *[
                            deposit.copy(index=index)
                            for index in range(deposit_count)
                        ]
                    ),
                ),
                # Constrain fixture size.
                include_receipts_in_output=False,
            )
        ],
    )
