"""
Type stubs for EIP checklist - auto-generated.

DO NOT EDIT MANUALLY - This file is generated by `uv run generate-checklist-stubs`
"""

from typing import Any, Callable, TypeVar, overload

import pytest

F = TypeVar("F", bound=Callable[..., Any])

class _CallableChecklistItem:
    """Base type for all callable checklist items."""

    @overload
    def __call__(self, func: F) -> F: ...
    @overload
    def __call__(self, *, eip: Any = ..., **kwargs: Any) -> pytest.MarkDecorator: ...
    def __str__(self) -> str: ...

class EIPChecklist:
    class BlobCountChanges(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            Eip4844BlobsChanges: _CallableChecklistItem

    class BlockBodyField(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            class ForkTransition(_CallableChecklistItem):
                After: _CallableChecklistItem
                Before: _CallableChecklistItem

            class ValueBehavior(_CallableChecklistItem):
                Accept: _CallableChecklistItem
                Reject: _CallableChecklistItem

    class BlockHeaderField(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            Genesis: _CallableChecklistItem

            class ForkTransition(_CallableChecklistItem):
                After: _CallableChecklistItem
                Before: _CallableChecklistItem
                Initial: _CallableChecklistItem

            class ValueBehavior(_CallableChecklistItem):
                Accept: _CallableChecklistItem
                Reject: _CallableChecklistItem

    class ExecutionLayerRequest(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            class CrossRequestType(_CallableChecklistItem):
                Update: _CallableChecklistItem

    class GasCostChanges(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            GasUpdatesMeasurement: _CallableChecklistItem
            OutOfGas: _CallableChecklistItem

            class ForkTransition(_CallableChecklistItem):
                After: _CallableChecklistItem
                Before: _CallableChecklistItem

    class GasRefundsChanges(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            class CrossFunctional(_CallableChecklistItem):
                CalldataCost: _CallableChecklistItem

            class ExceptionalAbort(_CallableChecklistItem):
                class NonRevertable(_CallableChecklistItem):
                    InvalidOpcode: _CallableChecklistItem
                    OutOfGas: _CallableChecklistItem
                    Revert: _CallableChecklistItem

                class Revertable(_CallableChecklistItem):
                    InvalidOpcode: _CallableChecklistItem
                    OutOfGas: _CallableChecklistItem
                    Revert: _CallableChecklistItem
                    UpperRevert: _CallableChecklistItem

            class RefundCalculation(_CallableChecklistItem):
                Exact: _CallableChecklistItem
                Over: _CallableChecklistItem
                Under: _CallableChecklistItem

    class General(_CallableChecklistItem):
        class CodeCoverage(_CallableChecklistItem):
            Eels: _CallableChecklistItem
            SecondClient: _CallableChecklistItem
            TestCoverage: _CallableChecklistItem

    class Opcode(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            ExceptionalAbort: _CallableChecklistItem
            StackOverflow: _CallableChecklistItem
            StackUnderflow: _CallableChecklistItem

            class ContractCreation(_CallableChecklistItem):
                Address: _CallableChecklistItem
                Recursive: _CallableChecklistItem

                class Failure(_CallableChecklistItem):
                    Collision: _CallableChecklistItem
                    InsufficientValue: _CallableChecklistItem
                    Oog: _CallableChecklistItem

            class DataPortion(_CallableChecklistItem):
                AllZeros: _CallableChecklistItem
                Jump: _CallableChecklistItem
                MaxValue: _CallableChecklistItem

            class ExecutionContext(_CallableChecklistItem):
                BlockContext: _CallableChecklistItem
                Call: _CallableChecklistItem
                Callcode: _CallableChecklistItem
                SetCode: _CallableChecklistItem
                TxContext: _CallableChecklistItem

                class Delegatecall(_CallableChecklistItem):
                    Balance: _CallableChecklistItem
                    Code: _CallableChecklistItem
                    Storage: _CallableChecklistItem

                class Initcode(_CallableChecklistItem):
                    Reentry: _CallableChecklistItem

                    class Behavior(_CallableChecklistItem):
                        Opcode: _CallableChecklistItem
                        Tx: _CallableChecklistItem

                class Staticcall(_CallableChecklistItem):
                    BanCheck: _CallableChecklistItem
                    BanNoModification: _CallableChecklistItem
                    SubCalls: _CallableChecklistItem

            class ForkTransition(_CallableChecklistItem):
                At: _CallableChecklistItem
                Invalid: _CallableChecklistItem

            class GasUsage(_CallableChecklistItem):
                MemoryExpansion: _CallableChecklistItem
                Normal: _CallableChecklistItem
                OutOfGasExecution: _CallableChecklistItem
                OutOfGasMemory: _CallableChecklistItem

                class OrderOfOperations(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Oog: _CallableChecklistItem

            class MemExp(_CallableChecklistItem):
                SingleByte: _CallableChecklistItem
                SixtyFourBytes: _CallableChecklistItem
                ThirtyOneBytes: _CallableChecklistItem
                ThirtyThreeBytes: _CallableChecklistItem
                ThirtyTwoBytes: _CallableChecklistItem
                TwoSixtyFourBytes: _CallableChecklistItem
                TwoSixtyFourMinusOneBytes: _CallableChecklistItem
                TwoThirtyTwoBytes: _CallableChecklistItem
                TwoThirtyTwoMinusOneBytes: _CallableChecklistItem
                TwoTwoFiftySixMinusOneBytes: _CallableChecklistItem
                ZeroBytesMaxOffset: _CallableChecklistItem
                ZeroBytesZeroOffset: _CallableChecklistItem

            class OutOfBounds(_CallableChecklistItem):
                class Verify(_CallableChecklistItem):
                    Max: _CallableChecklistItem
                    MaxPlusOne: _CallableChecklistItem

            class ReturnData(_CallableChecklistItem):
                class Buffer(_CallableChecklistItem):
                    Current: _CallableChecklistItem
                    Parent: _CallableChecklistItem

            class StackComplexOperations(_CallableChecklistItem):
                class DataPortionVariables(_CallableChecklistItem):
                    Bottom: _CallableChecklistItem
                    Middle: _CallableChecklistItem
                    Top: _CallableChecklistItem

                class StackHeights(_CallableChecklistItem):
                    Even: _CallableChecklistItem
                    Odd: _CallableChecklistItem
                    Zero: _CallableChecklistItem

            class Terminating(_CallableChecklistItem):
                class Rollback(_CallableChecklistItem):
                    Balance: _CallableChecklistItem
                    Contracts: _CallableChecklistItem
                    Logs: _CallableChecklistItem
                    Nonce: _CallableChecklistItem
                    Storage: _CallableChecklistItem

                class Scenarios(_CallableChecklistItem):
                    Initcode: _CallableChecklistItem
                    SubLevel: _CallableChecklistItem
                    TopLevel: _CallableChecklistItem

    class Precompile(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            ExcessiveGasUsage: _CallableChecklistItem

            class CallContexts(_CallableChecklistItem):
                Callcode: _CallableChecklistItem
                Delegate: _CallableChecklistItem
                Normal: _CallableChecklistItem
                SetCode: _CallableChecklistItem
                Static: _CallableChecklistItem
                TxEntry: _CallableChecklistItem

                class Initcode(_CallableChecklistItem):
                    CREATE: _CallableChecklistItem
                    Tx: _CallableChecklistItem

            class ForkTransition(_CallableChecklistItem):
                class After(_CallableChecklistItem):
                    Warm: _CallableChecklistItem

                class Before(_CallableChecklistItem):
                    Cold: _CallableChecklistItem
                    InvalidInput: _CallableChecklistItem
                    ZeroGas: _CallableChecklistItem

            class GasUsage(_CallableChecklistItem):
                class Constant(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Oog: _CallableChecklistItem

                class Dynamic(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Oog: _CallableChecklistItem

            class InputLengths(_CallableChecklistItem):
                Zero: _CallableChecklistItem

                class Dynamic(_CallableChecklistItem):
                    TooLong: _CallableChecklistItem
                    TooShort: _CallableChecklistItem
                    Valid: _CallableChecklistItem

                class Static(_CallableChecklistItem):
                    Correct: _CallableChecklistItem
                    TooLong: _CallableChecklistItem
                    TooShort: _CallableChecklistItem

            class Inputs(_CallableChecklistItem):
                AllZeros: _CallableChecklistItem
                MaxValues: _CallableChecklistItem

                class Invalid(_CallableChecklistItem):
                    Corrupted: _CallableChecklistItem
                    Crypto: _CallableChecklistItem

                class Valid(_CallableChecklistItem):
                    Boundary: _CallableChecklistItem
                    Crypto: _CallableChecklistItem

            class OutOfBounds(_CallableChecklistItem):
                Max: _CallableChecklistItem
                MaxPlusOne: _CallableChecklistItem

            class ValueTransfer(_CallableChecklistItem):
                NoFee: _CallableChecklistItem

                class Fee(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Over: _CallableChecklistItem
                    Under: _CallableChecklistItem

    class RemovedPrecompile(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            class ForkTransition(_CallableChecklistItem):
                Operational: _CallableChecklistItem

                class After(_CallableChecklistItem):
                    Cold: _CallableChecklistItem

                class Before(_CallableChecklistItem):
                    Warm: _CallableChecklistItem

    class SystemContract(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            class CallContexts(_CallableChecklistItem):
                Callcode: _CallableChecklistItem
                Delegate: _CallableChecklistItem
                Normal: _CallableChecklistItem
                SetCode: _CallableChecklistItem
                Static: _CallableChecklistItem
                TxEntry: _CallableChecklistItem

                class Initcode(_CallableChecklistItem):
                    CREATE: _CallableChecklistItem
                    Tx: _CallableChecklistItem

            class ContractSubstitution(_CallableChecklistItem):
                GasLimitFailure: _CallableChecklistItem
                GasLimitSuccess: _CallableChecklistItem
                Logs: _CallableChecklistItem
                RaisesException: _CallableChecklistItem
                ReturnLengths: _CallableChecklistItem

            class ContractVariations(_CallableChecklistItem):
                Networks: _CallableChecklistItem

            class Deployment(_CallableChecklistItem):
                Address: _CallableChecklistItem
                Missing: _CallableChecklistItem

            class ExcessiveGas(_CallableChecklistItem):
                BlockGas: _CallableChecklistItem
                SystemCall: _CallableChecklistItem

            class ForkTransition(_CallableChecklistItem):
                CallBeforeFork: _CallableChecklistItem

            class GasUsage(_CallableChecklistItem):
                class Constant(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Oog: _CallableChecklistItem

                class Dynamic(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Oog: _CallableChecklistItem

            class InputLengths(_CallableChecklistItem):
                Zero: _CallableChecklistItem

                class Dynamic(_CallableChecklistItem):
                    TooLong: _CallableChecklistItem
                    TooShort: _CallableChecklistItem
                    Valid: _CallableChecklistItem

                class Static(_CallableChecklistItem):
                    Correct: _CallableChecklistItem
                    TooLong: _CallableChecklistItem
                    TooShort: _CallableChecklistItem

            class Inputs(_CallableChecklistItem):
                AllZeros: _CallableChecklistItem
                Boundary: _CallableChecklistItem
                MaxValues: _CallableChecklistItem
                Valid: _CallableChecklistItem

                class Invalid(_CallableChecklistItem):
                    Checks: _CallableChecklistItem
                    Corrupted: _CallableChecklistItem
                    Crypto: _CallableChecklistItem

            class OutOfBounds(_CallableChecklistItem):
                Max: _CallableChecklistItem
                MaxPlusOne: _CallableChecklistItem

            class ValueTransfer(_CallableChecklistItem):
                NoFee: _CallableChecklistItem

                class Fee(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Over: _CallableChecklistItem
                    Under: _CallableChecklistItem

    class TransactionType(_CallableChecklistItem):
        class Test(_CallableChecklistItem):
            ContractCreation: _CallableChecklistItem

            class BlockInteractions(_CallableChecklistItem):
                MixedTxs: _CallableChecklistItem

                class Eip7825(_CallableChecklistItem):
                    Invalid: _CallableChecklistItem
                    Valid: _CallableChecklistItem

                class LastTx(_CallableChecklistItem):
                    Invalid: _CallableChecklistItem
                    Valid: _CallableChecklistItem

                class SingleTx(_CallableChecklistItem):
                    Invalid: _CallableChecklistItem
                    Valid: _CallableChecklistItem

            class Encoding(_CallableChecklistItem):
                ExtraBytes: _CallableChecklistItem
                ExtraFields: _CallableChecklistItem
                MissingFields: _CallableChecklistItem
                Truncated: _CallableChecklistItem

                class FieldSizes(_CallableChecklistItem):
                    LeadingZero: _CallableChecklistItem
                    RemoveByte: _CallableChecklistItem

                class ListField(_CallableChecklistItem):
                    Max: _CallableChecklistItem
                    MaxPlusOne: _CallableChecklistItem
                    Zero: _CallableChecklistItem

                class NewTypes(_CallableChecklistItem):
                    IncorrectEncoding: _CallableChecklistItem

            class ForkTransition(_CallableChecklistItem):
                Before: _CallableChecklistItem

            class IntrinsicValidity(_CallableChecklistItem):
                ChainId: _CallableChecklistItem
                DataFloorAboveIntrinsicGasCost: _CallableChecklistItem
                NonceExact: _CallableChecklistItem
                NonceMinusOne: _CallableChecklistItem
                NoncePlusOne: _CallableChecklistItem
                To: _CallableChecklistItem
                ValueNonZeroInsufficientBalance: _CallableChecklistItem
                ValueNonZeroSufficientBalance: _CallableChecklistItem
                ValueZeroInsufficientBalance: _CallableChecklistItem
                ValueZeroSufficientBalance: _CallableChecklistItem

                class GasLimit(_CallableChecklistItem):
                    Exact: _CallableChecklistItem
                    Insufficient: _CallableChecklistItem

                class MaxFee(_CallableChecklistItem):
                    BaseEqual: _CallableChecklistItem
                    BaseLower: _CallableChecklistItem
                    MaxPriorityEqualToMaxFee: _CallableChecklistItem
                    MaxPriorityLowerThanMaxFee: _CallableChecklistItem

            class OutOfBounds(_CallableChecklistItem):
                Max: _CallableChecklistItem
                MaxPlusOne: _CallableChecklistItem

            class SenderAccount(_CallableChecklistItem):
                Balance: _CallableChecklistItem
                Nonce: _CallableChecklistItem

            class Signature(_CallableChecklistItem):
                class Invalid(_CallableChecklistItem):
                    FieldOutsideCurve: _CallableChecklistItem

                    class R(_CallableChecklistItem):
                        Max: _CallableChecklistItem
                        MaxMinusOne: _CallableChecklistItem
                        Secp256k1n: _CallableChecklistItem
                        Secp256k1nMinusOne: _CallableChecklistItem
                        Secp256k1nPlusOne: _CallableChecklistItem
                        Zero: _CallableChecklistItem

                    class S(_CallableChecklistItem):
                        Complement: _CallableChecklistItem
                        Max: _CallableChecklistItem
                        MaxMinusOne: _CallableChecklistItem
                        Secp256k1n: _CallableChecklistItem
                        Secp256k1nHalf: _CallableChecklistItem
                        Secp256k1nHalfMinusOne: _CallableChecklistItem
                        Secp256k1nHalfPlusOne: _CallableChecklistItem
                        Secp256k1nMinusOne: _CallableChecklistItem
                        Secp256k1nPlusOne: _CallableChecklistItem
                        Zero: _CallableChecklistItem

                    class V(_CallableChecklistItem):
                        Max: _CallableChecklistItem
                        ThirtyFive: _CallableChecklistItem
                        ThirtySix: _CallableChecklistItem
                        TwentyEight: _CallableChecklistItem
                        TwentySeven: _CallableChecklistItem
                        Two: _CallableChecklistItem

            class TxScopedAttributes(_CallableChecklistItem):
                OlderTxTypes: _CallableChecklistItem
                Read: _CallableChecklistItem

                class Persistent(_CallableChecklistItem):
                    Reset: _CallableChecklistItem
                    Throughout: _CallableChecklistItem
