"""
Ethereum Virtual Machine (EVM) Gas Constants.

.. contents:: Table of Contents
    :backlinks: none
    :local:

Introduction
------------

EVM gas constants.
"""

from ethereum_types.numeric import Uint

GAS_JUMPDEST = Uint(1)
GAS_BASE = Uint(2)
GAS_VERY_LOW = Uint(3)
GAS_LOW = Uint(5)
GAS_MID = Uint(8)
GAS_HIGH = Uint(10)
GAS_EXPONENTIATION = Uint(10)
GAS_KECCAK256 = Uint(30)
GAS_COLD_ACCOUNT_ACCESS = Uint(2600)
GAS_BLOCK_HASH = Uint(20)
GAS_STORAGE_SET = Uint(20000)
GAS_WARM_ACCESS = Uint(100)
GAS_COLD_SLOAD = Uint(2100)
GAS_LOG = Uint(375)
GAS_CREATE = Uint(32000)
GAS_SELF_DESTRUCT = Uint(5000)

"""
Opcode to Gas Category Mappings
"""
OP_STOP = GAS_BASE
OP_ADD = GAS_VERY_LOW
OP_MUL = GAS_LOW
OP_SUB = GAS_VERY_LOW
OP_DIV = GAS_LOW
OP_SDIV = GAS_LOW
OP_MOD = GAS_LOW
OP_SMOD = GAS_LOW
OP_ADDMOD = GAS_MID
OP_MULMOD = GAS_MID
OP_EXP = GAS_EXPONENTIATION
OP_SIGNEXTEND = GAS_LOW

# Comparison operations
OP_LT = GAS_VERY_LOW
OP_GT = GAS_VERY_LOW
OP_SLT = GAS_VERY_LOW
OP_SGT = GAS_VERY_LOW
OP_EQ = GAS_VERY_LOW
OP_ISZERO = GAS_VERY_LOW

# Bitwise operations
OP_AND = GAS_VERY_LOW
OP_OR = GAS_VERY_LOW
OP_XOR = GAS_VERY_LOW
OP_NOT = GAS_VERY_LOW
OP_BYTE = GAS_VERY_LOW
OP_SHL = GAS_VERY_LOW
OP_SHR = GAS_VERY_LOW
OP_SAR = GAS_VERY_LOW
OP_CLZ = GAS_LOW

# Keccak operation
OP_KECCAK = GAS_KECCAK256  # 0x20 - plus GAS_KECCAK256_WORD per word

# Environmental operations
OP_ADDRESS = GAS_BASE
OP_BALANCE = GAS_COLD_ACCOUNT_ACCESS
OP_ORIGIN = GAS_BASE
OP_CALLER = GAS_BASE
OP_CALLVALUE = GAS_BASE
OP_CALLDATALOAD = GAS_VERY_LOW
OP_CALLDATASIZE = GAS_BASE
OP_CALLDATACOPY = GAS_VERY_LOW
OP_CODESIZE = GAS_BASE
OP_CODECOPY = GAS_VERY_LOW
OP_GASPRICE = GAS_BASE
OP_EXTCODESIZE = GAS_COLD_ACCOUNT_ACCESS
OP_EXTCODECOPY = GAS_COLD_ACCOUNT_ACCESS
OP_RETURNDATASIZE = GAS_BASE
OP_RETURNDATACOPY = GAS_VERY_LOW
OP_EXTCODEHASH = GAS_COLD_ACCOUNT_ACCESS

# Block operations
OP_BLOCKHASH = GAS_BLOCK_HASH
OP_COINBASE = GAS_BASE
OP_TIMESTAMP = GAS_BASE
OP_NUMBER = GAS_BASE
OP_PREVRANDAO = GAS_BASE
OP_GASLIMIT = GAS_BASE
OP_CHAINID = GAS_BASE
OP_SELFBALANCE = GAS_LOW
OP_BASEFEE = GAS_BASE
OP_BLOBHASH = GAS_BASE
OP_BLOBBASEFEE = GAS_BASE

# Memory operations
OP_MLOAD = GAS_VERY_LOW
OP_MSTORE = GAS_VERY_LOW
OP_MSTORE8 = GAS_VERY_LOW
OP_MSIZE = GAS_BASE
OP_MCOPY = GAS_VERY_LOW

# Stack operations
OP_POP = GAS_BASE

# Storage operations
OP_SLOAD = GAS_COLD_SLOAD
OP_SSTORE = GAS_STORAGE_SET
OP_TLOAD = GAS_WARM_ACCESS
OP_TSTORE = GAS_WARM_ACCESS

# Control flow operations
OP_JUMP = GAS_MID
OP_JUMPI = GAS_HIGH
OP_PC = GAS_BASE
OP_GAS = GAS_BASE
OP_JUMPDEST = GAS_JUMPDEST

# Push operations
OP_PUSH0 = GAS_BASE
OP_PUSH = GAS_VERY_LOW

# DUP1-16 operations
OP_DUP = GAS_VERY_LOW

# Swap operations
OP_SWAP = GAS_VERY_LOW

# Log operations
OP_LOG0 = GAS_LOG

# System operations
OP_CREATE = GAS_CREATE
OP_CALL = GAS_COLD_ACCOUNT_ACCESS
OP_CALLCODE = GAS_COLD_ACCOUNT_ACCESS
OP_RETURN = GAS_BASE
OP_DELEGATECALL = GAS_COLD_ACCOUNT_ACCESS
OP_CREATE2 = GAS_CREATE
OP_STATICCALL = GAS_COLD_ACCOUNT_ACCESS
OP_REVERT = GAS_BASE
OP_SELFDESTRUCT = GAS_SELF_DESTRUCT
