"""Test suite for the `GasConsumer` class."""

import pytest

from execution_testing.forks import (
    Amsterdam,
    Fork,
    Osaka,
    Shanghai,
    get_forks,
)
from execution_testing.forks.base_fork import (
    MemoryExpansionGasCalculator,
)
from execution_testing.vm import Op

from ..tools_code import GasConsumer
from ..tools_code.generators import UNPAYABLE_GAS

GAS_TARGETS = [0, 1, 5, 11, 12, 13, 100, 1_000, 100_000, 30_000_000]


@pytest.mark.parametrize("gas", GAS_TARGETS)
@pytest.mark.parametrize("fork", get_forks(), ids=lambda fork: fork.name())
def test_gas_consumer_exact_cost(fork: Fork, gas: int) -> None:
    """Verify the generated bytecode costs exactly the requested gas."""
    assert GasConsumer(gas=gas, fork=fork).gas_cost(fork) == gas


@pytest.mark.parametrize("gas", GAS_TARGETS)
def test_gas_consumer_leaves_no_state_gas(gas: int) -> None:
    """Verify the whole target lands on the execution dimension."""
    consumer = GasConsumer(gas=gas, fork=Amsterdam)
    assert consumer.state_cost(Amsterdam) == 0
    assert consumer.execution_cost(Amsterdam) == gas


@pytest.mark.parametrize(
    "gas,expected_length",
    [
        pytest.param(0, 0, id="nothing_to_consume"),
        pytest.param(5, 5, id="below_the_cheapest_expansion"),
        pytest.param(11, 11, id="one_gas_below_the_cheapest_expansion"),
        pytest.param(12, 5, id="the_cheapest_expansion"),
    ],
)
def test_gas_consumer_small_targets(gas: int, expected_length: int) -> None:
    """
    Verify targets too small for a memory expansion fall back to `JUMPDEST`.

    One word of expansion costs 12 gas at `Shanghai`: three each for the
    two pushes and the `MSTORE8`, and three for the word.
    """
    consumer = GasConsumer(gas=gas, fork=Shanghai)
    assert len(consumer) == expected_length
    assert consumer.gas_cost(Shanghai) == gas
    if gas < 12:
        assert bytes(consumer) == bytes(Op.JUMPDEST) * gas


def test_gas_consumer_is_compact() -> None:
    """Verify a block-sized target does not make a block-sized contract."""
    consumer = GasConsumer(gas=30_000_000, fork=Osaka)
    assert len(consumer) < 1_000


@pytest.mark.parametrize("previous_memory_size", [32, 1_000, 100_000])
def test_gas_consumer_previous_memory_size(previous_memory_size: int) -> None:
    """
    Verify an already expanded memory is accounted for.

    The consumer is charged only for the words it adds on top, so it still
    costs its target and differs from the empty-memory bytecode.
    """
    prefix = Op.MSTORE8(
        previous_memory_size - 1, 0, new_memory_size=previous_memory_size
    )
    consumer = GasConsumer(
        gas=100_000, fork=Osaka, previous_memory_size=previous_memory_size
    )
    assert (prefix + consumer).gas_cost(Osaka) == (
        prefix.gas_cost(Osaka) + 100_000
    )
    assert bytes(consumer) != bytes(GasConsumer(gas=100_000, fork=Osaka))


def test_gas_consumer_composes() -> None:
    """Verify a consumer appended to other code still costs its target."""
    prefix = Op.SSTORE(0, 1)
    consumer = GasConsumer(gas=70_000, fork=Osaka)
    assert (prefix + consumer).gas_cost(Osaka) == (
        prefix.gas_cost(Osaka) + 70_000
    )


@pytest.mark.parametrize("fork", get_forks(), ids=lambda fork: fork.name())
def test_gas_consumer_out_of_gas(fork: Fork) -> None:
    """
    Verify the `None` sentinel produces bytecode that cannot be paid for.

    The expansion is sized against the fork's own pricing, so the charge
    stays out of reach however the schedule moves.
    """
    consumer = GasConsumer(gas=None, fork=fork)
    assert consumer.gas is None
    assert consumer.gas_cost(fork) > UNPAYABLE_GAS


def test_gas_consumer_out_of_gas_needs_an_unpayable_expansion() -> None:
    """
    Verify a fork that caps the expansion charge is rejected, loudly.

    Such a fork must be noticed, not silently handed bytecode that runs to
    completion.
    """

    class CappedMemory(Osaka):
        """A fork that caps the expansion charge at one word."""

        @classmethod
        def memory_expansion_gas_calculator(
            cls,
        ) -> MemoryExpansionGasCalculator:
            """Return the capped calculator."""
            uncapped = Osaka.memory_expansion_gas_calculator()

            def fn(*, new_bytes: int, previous_bytes: int = 0) -> int:
                return min(
                    uncapped(
                        new_bytes=new_bytes, previous_bytes=previous_bytes
                    ),
                    3,
                )

            return fn

    with pytest.raises(ValueError, match="too cheaply"):
        GasConsumer(gas=None, fork=CappedMemory)


def test_gas_consumer_negative_gas() -> None:
    """Verify a negative gas target is rejected."""
    with pytest.raises(ValueError, match="negative gas target"):
        GasConsumer(gas=-1, fork=Osaka)
