"""
Fork rules for consume hive simulators.

TODO: Create the ruleset dynamically per fixture test case based on the fork.
Remove this file afterwards.
"""

from typing import Dict, List

from ethereum_test_forks import Cancun, Fork, Osaka, Prague


def get_blob_schedule_entries(fork: Fork) -> Dict[str, int]:
    """
    Generate blob schedule entries for each fork (and respective parent forks).

    Adds the following entries to the ruleset for the given fork (and parent forks):
        HIVE_{FORK}_BLOB_TARGET: target_blobs_per_block()
        HIVE_{FORK}_BLOB_MAX: max_blobs_per_block()
        HIVE_{FORK}_BLOB_BASE_FEE_UPDATE_FRACTION: blob_base_fee_update_fraction()
    """
    entries: Dict = {}
    forks_with_blobs: List[Fork] = []
    current_fork = fork
    while current_fork.supports_blobs():
        forks_with_blobs.append(current_fork)
        current_fork = current_fork.parent()  # type: ignore

    for fork_to_process in forks_with_blobs:
        prefix = fork_to_process.__name__.upper()
        entries[f"HIVE_{prefix}_BLOB_TARGET"] = fork_to_process.target_blobs_per_block()
        entries[f"HIVE_{prefix}_BLOB_MAX"] = fork_to_process.max_blobs_per_block()
        entries[f"HIVE_{prefix}_BLOB_BASE_FEE_UPDATE_FRACTION"] = (
            fork_to_process.blob_base_fee_update_fraction()
        )
    return entries


ruleset = {
    "Frontier": {
        "HIVE_FORK_HOMESTEAD": 2000,
        "HIVE_FORK_DAO_BLOCK": 2000,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "Homestead": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_DAO_BLOCK": 2000,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "EIP150": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "EIP158": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "Byzantium": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "Constantinople": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "ConstantinopleFix": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "Istanbul": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "Berlin": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 2000,
    },
    "FrontierToHomesteadAt5": {
        "HIVE_FORK_HOMESTEAD": 5,
        "HIVE_FORK_DAO_BLOCK": 2000,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "HomesteadToEIP150At5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 5,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "HomesteadToDaoAt5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_DAO_BLOCK": 5,
        "HIVE_FORK_TANGERINE": 2000,
        "HIVE_FORK_SPURIOUS": 2000,
        "HIVE_FORK_BYZANTIUM": 2000,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "EIP158ToByzantiumAt5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 5,
        "HIVE_FORK_CONSTANTINOPLE": 2000,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "ByzantiumToConstantinopleAt5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 5,
        "HIVE_FORK_PETERSBURG": 2000,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "ByzantiumToConstantinopleFixAt5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 5,
        "HIVE_FORK_PETERSBURG": 5,
        "HIVE_FORK_ISTANBUL": 2000,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "ConstantinopleFixToIstanbulAt5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 5,
        "HIVE_FORK_BERLIN": 2000,
        "HIVE_FORK_LONDON": 2000,
    },
    "IstanbulToBerlinAt5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 5,
        "HIVE_FORK_LONDON": 2000,
    },
    "BerlinToLondonAt5": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 5,
    },
    "London": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
    },
    "ArrowGlacierToMergeAtDiffC0000": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 786432,
    },
    "Merge": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
    },
    "Paris": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
    },
    "Shanghai": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
    },
    "ParisToShanghaiAtTime15k": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 15000,
    },
    "Cancun": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        **get_blob_schedule_entries(Cancun),
    },
    "ShanghaiToCancunAtTime15k": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 15000,
        **get_blob_schedule_entries(Cancun),
    },
    "Prague": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        **get_blob_schedule_entries(Prague),
    },
    "CancunToPragueAtTime15k": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 15000,
        **get_blob_schedule_entries(Prague),
    },
    "Osaka": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 0,
        **get_blob_schedule_entries(Osaka),
    },
    "PragueToOsakaAtTime15k": {
        "HIVE_FORK_HOMESTEAD": 0,
        "HIVE_FORK_TANGERINE": 0,
        "HIVE_FORK_SPURIOUS": 0,
        "HIVE_FORK_BYZANTIUM": 0,
        "HIVE_FORK_CONSTANTINOPLE": 0,
        "HIVE_FORK_PETERSBURG": 0,
        "HIVE_FORK_ISTANBUL": 0,
        "HIVE_FORK_BERLIN": 0,
        "HIVE_FORK_LONDON": 0,
        "HIVE_FORK_MERGE": 0,
        "HIVE_TERMINAL_TOTAL_DIFFICULTY": 0,
        "HIVE_SHANGHAI_TIMESTAMP": 0,
        "HIVE_CANCUN_TIMESTAMP": 0,
        "HIVE_PRAGUE_TIMESTAMP": 0,
        "HIVE_OSAKA_TIMESTAMP": 15000,
        **get_blob_schedule_entries(Osaka),
    },
}
