name: BAL Devnet 2

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  create-devnet-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge EIP branches into devnet
        uses: ./.github/actions/merge-eip-branches
        with:
          fork: amsterdam
          devnet_name: bal/2
          eip_numbers: 8024,7843,7708,7778
