name: Benchmarking

on:
  push:
    branches:
      - "benchmarks/**"
    paths-ignore: &non_benchmark_paths
      - "**.md"
      - "LICENSE*"
      - ".gitignore"
      - ".vscode/**"
      - "whitelist.txt"
      - "docs/**"
      - "mkdocs.yml"
  pull_request:
    branches:
      - "benchmarks/**"
    paths-ignore: *non_benchmark_paths
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  sanity-checks:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Benchmark Gas Values
            recipe: bench-gas
          - name: Fixed Opcode Count CLI
            recipe: bench-opcode
          - name: Fixed Opcode Count Config
            recipe: bench-opcode-config
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - uses: ./.github/actions/setup-uv
        with:
          enable-cache: "false"

      - name: Install PyPy for bench-gas json_loader verify
        if: matrix.recipe == 'bench-gas'
        shell: bash
        run: uv python install pypy3.11

      - uses: ./.github/actions/build-evm-base
        id: evm-builder
        with:
          type: benchmark

      - name: Run ${{ matrix.name }}
        run: just ${{ matrix.recipe }}
        env:
          EVM_BIN: ${{ steps.evm-builder.outputs.evm-bin }}

  # TODO: Add execute remote tests with --gas-benchmark-values
  # TODO: Add execute remote tests with --fixed-opcode-count

  build-artifact:
    name: Build Benchmark Fixture Artifact
    needs: [ sanity-checks ] # TODO: Add execute remote jobs when implemented
    if: github.event_name == 'push'
    runs-on: [ self-hosted-ghr, size-gigachungus-x64 ]
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - uses: ./.github/actions/build-fixtures
        with:
          release_name: benchmark_fast
