name: Benchmark Release Sanity Check

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  release-check:
    name: Benchmark Release Sanity Check
    runs-on: [self-hosted-ghr, size-gigachungus-x64]
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - uses: ./.github/actions/build-fixtures
        with:
          release_name: benchmark
